service : aws-lambda-nodeAPI

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 memorySize: 512
 timeout: 15
 stage: production
 region: us-east-2 # AWS region

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'